backend:
  name: github
  repo: betagouv/svair-mock-data
  open_authoring: true

publish_mode: editorial_workflow

media_folder: public/media

show_preview_links: false

collections:
  - name: "people"
    label: "Déclarant"
    description: "Personnes présentes sur l'avis d'imposition"
    folder: "data/people"
    create: true
    extension: json
    format: json
    identifier_field: "id"
    slug: "{{id}}"
    summary: "{{name}} {{surname}} né(e) le {{birthdate}}"
    editor:
      preview: false
    fields:
      - label: "ID"
        name: "id"
        widget: "id"
      - label: "Nom de famille"
        name: "surname"
        widget: "string"
      - label: "Nom de naissance"
        name: "birthname"
        widget: "string"
      - label: "Prénom"
        name: "name"
        widget: "string"
      - label: "Date de naissance"
        name: "birthdate"
        widget: "date"
        format: "DD/MM/YYYY"
  - name: "addresses"
    label: "Adresse"
    description: "Adresses fiscales"
    folder: "data/addresses"
    create: true
    extension: json
    format: json
    identifier_field: "id"
    slug: "{{id}}"
    summary: "{{line1}} {{zipCode}} {{city}}"
    editor:
      preview: false
    fields:
      - label: "ID"
        name: "id"
        widget: "id"
      - label: "Numéro et nom de voie"
        name: "line1"
        widget: "string"
      - label: "Code postal"
        name: "zipCode"
        widget: "string"
      - label: "Commune"
        name: "city"
        widget: "string"
  - name: "notices"
    label: "Avis"
    description: "Liste des avis requêtables"
    folder: "data/notices"
    create: true
    extension: json
    format: json
    identifier_field: "noticeNumber"
    slug: "{{taxNumber}}_{{noticeNumber}}"
    summary: "Numéro fiscal : {{taxNumber}} - numéro d'avis : {{noticeNumber}} - année d'imposition : {{taxYear}}"
    editor:
      preview: false
    fields:
      - label: "Numéro fiscal"
        name: "taxNumber"
        widget: "tax-number"
      - label: "Numéro d'avis"
        name: "noticeNumber"
        widget: "notice-number"
      - label: "Déclarant 1"
        name: "person1"
        widget: "relation"
        collection: "people"
        searchFields:
          - "surname"
          - "birthname"
          - "name"
        displayFields:
          - "surname"
          - "name"
        valueField: "id"
      - label: "Déclarant 2"
        name: "person2"
        widget: "relation"
        collection: "people"
        required: false
        searchFields:
          - "surname"
          - "birthname"
          - "name"
        displayFields:
          - "surname"
          - "name"
        valueField: "id"
      - label: "Adresse"
        name: "address"
        widget: "relation"
        collection: "addresses"
        searchFields:
          - "line1"
          - "zipCode"
          - "city"
        displayFields:
          - "line1"
          - "zipCode"
          - "city"
        valueField: "id"
      - label: "Année d'imposition"
        name: "taxYear"
        widget: "number"
        valueType: "int"
        min: 2000
        max: 3000
      - label: "Année des revenus"
        name: "earningsYear"
        widget: "number"
        valueType: "int"
        min: 2000
        max: 3000
      - label: "Date de recouvrement"
        name: "recoveryDate"
        widget: "date"
        format: "DD/MM/YYYY"
      - label: "Date d'établissement"
        name: "statementDate"
        widget: "date"
        format: "DD/MM/YYYY"
      - label: "Nombre de parts"
        name: "parts"
        widget: "number"
        valueType: "int"
        min: 1
      - label: "Situation familiale"
        name: "familyComposition"
        widget: "select"
        options:
          - "Célibataire"
          - "Marié(e)s"
      - label: "Nombre de personnes à charge"
        name: "dependents"
        widget: "number"
        valueType: "int"
        min: 1
      - label: "Revenu brut global"
        name: "globalEarnings"
        widget: "number"
        valueType: "int"
        min: 0
      - label: "Revenu imposable"
        name: "taxableEarnings"
        widget: "number"
        valueType: "int"
        min: 0
      - label: "Impôts nets avant correction"
        name: "taxBeforeCorrection"
        widget: "object"
        fields:
          - label: "Imposable"
            name: "taxable"
            widget: "boolean"
          - label: "Montant"
            name: "amount"
            widget: "number"
            valueType: "int"
            min: 0
            required: false
      - label: "Impôts"
        name: "tax"
        widget: "object"
        fields:
          - label: "Imposable"
            name: "taxable"
            widget: "boolean"
          - label: "Montant"
            name: "amount"
            widget: "number"
            valueType: "int"
            min: 0
            required: false
      - label: "Revenu fiscal de référence"
        name: "referenceEarnings"
        widget: "number"
        valueType: "int"
        min: 0
      - label: "Situation partielle"
        name: "partialSituation"
        widget: "text"
        required: false
      - label: "Erreur correctif"
        name: "correctionError"
        widget: "text"
        required: false
